server {
    listen 9000;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
        add_header X-Content-Type-Options nosniff;
    }

    # Allow directory listing for samples
    location /samples/ {
        autoindex on;
    }
}
